# Generated by Django 4.1.2 on 2022-11-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название книги')),
                ('cover', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Фото обложки книги')),
                ('prise', models.FloatField(verbose_name='Стоимость книги')),
                ('start_date', models.DateField(verbose_name='Дата записи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
    ]
