# Generated by Django 4.1.2 on 2022-11-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0010_author_cover'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_book',
            field=models.ManyToManyField(blank=True, related_name='books', to='reference_books.author'),
        ),
    ]
