# Generated by Django 4.1.2 on 2022-11-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0010_author_cover'),
        ('book', '0002_book_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='serie_book',
            field=models.ManyToManyField(blank=True, related_name='books', to='reference_books.serie', verbose_name='Серия книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_book',
            field=models.ManyToManyField(blank=True, related_name='books', to='reference_books.author', verbose_name='Автор(ы) книги'),
        ),
    ]
