# Generated by Django 4.1.2 on 2022-11-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0010_author_cover'),
        ('book', '0003_book_serie_book_alter_book_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='serie_book',
        ),
        migrations.AddField(
            model_name='book',
            name='serie_book',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reference_books.serie', verbose_name='Серия книги'),
            preserve_default=False,
        ),
    ]
