# Generated by Django 4.1.2 on 2022-11-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0010_author_cover'),
        ('book', '0004_remove_book_serie_book_book_serie_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_book',
            field=models.ManyToManyField(related_name='books', to='reference_books.author', verbose_name='Автор(ы) книги'),
        ),
    ]
