# Generated by Django 4.1.2 on 2022-11-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0010_author_cover'),
        ('book', '0005_alter_book_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre_book',
            field=models.ManyToManyField(related_name='books', to='reference_books.genre', verbose_name='Жанр(ы) книги'),
        ),
    ]
