# Generated by Django 4.1.2 on 2022-11-13 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0010_author_cover'),
        ('book', '0006_book_genre_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='start_date',
        ),
        migrations.AddField(
            model_name='book',
            name='age_restrictions',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Возрастные ограничения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='binding_book',
            field=models.CharField(default=0, max_length=60, verbose_name='Переплет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='date_change',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='book',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата внесения в каталог'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='format_book',
            field=models.CharField(default=0, max_length=60, verbose_name='Формат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_book',
            field=models.CharField(default=0, max_length=30, verbose_name='ISBN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_books',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество книг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество страниц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reference_books.publishing', verbose_name='Издательство книги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='weight_book',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Вес книги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year_of_publishing',
            field=models.DateField(default='2022-11-13', verbose_name='Год издания'),
            preserve_default=False,
        ),
    ]
