# Generated by Django 4.1.2 on 2022-11-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0010_author_cover'),
        ('book', '0007_remove_book_description_remove_book_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_book',
            field=models.ManyToManyField(related_name='author_books', to='reference_books.author', verbose_name='Автор(ы) книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='covers/%Y/%m/%d/', verbose_name='Фото обложки книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre_book',
            field=models.ManyToManyField(related_name='genre_books', to='reference_books.genre', verbose_name='Жанр(ы) книги'),
        ),
    ]
