# Generated by Django 4.1.2 on 2022-11-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_author_book_alter_book_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='prise',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Стоимость книги'),
            preserve_default=False,
        ),
    ]
