# Generated by Django 4.1.2 on 2022-10-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reference_Books',
            new_name='Author',
        ),
    ]
