# Generated by Django 4.1.2 on 2022-10-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0004_genre_publishing_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='start_date',
            field=models.DateField(default='2022-10-11'),
            preserve_default=False,
        ),
    ]
