# Generated by Django 4.1.2 on 2022-10-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0005_author_description_author_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
