# Generated by Django 4.1.2 on 2022-11-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0009_alter_genre_name_alter_serie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='cover',
            field=models.ImageField(default='sdf', upload_to='uploads/%Y/%m/%d/', verbose_name='Author cover'),
            preserve_default=False,
        ),
    ]
