# Generated by Django 4.1.2 on 2022-11-28 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_author_book_alter_book_cover_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Created date')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='orders.basket', verbose_name='Корзина')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.book', verbose_name='Книги в корзине')),
            ],
        ),
    ]
